#! /bin/bash
oids=("${@:2}")
unbuffer /tmp/A2/prober $1 $2 -1 ${@:3} | while read res;do
top=`echo $res | cut -d"|" -f1 | perl -pe 'chomp' | tr -d '[:space:]'`
top=${top%.*}
zop=000000000
top=$top$zop
IFS='|' read -ra differ <<< "$res"
for ((i=1;i<${#differ[@]};i++))
do
	values=`echo ${differ[$i]} | tr -d '[:space:]'`
	printf "rate,oid=${oids[$i]} value=$values $top\n" >> influx
done
curl -i -XPOST 'http://localhost:8086/write?db=A3' -u ats:atslabb00 --data-binary @influx
rm influx
done




